[package]
name = "crush"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow     = "1.0.103"
bytes      = "1.12.1"
directories= "6.0.0"
libc = "0.2.189"
rustyline  = "18.0.1"
serde      = { version = "1.0", features = ["derive"] }
shlex      = "2.0.1"
thiserror  = "2.0.18"
toml       = "0.8"
which      = "8.0.4"
