[package]
name = "crush"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow     = "1.0.103"
directories= "6.0.0"
libc = "0.2.189"
rustyline  = { version = "18.0.1", default-features = false, features = ["with-file-history", "custom-bindings"] }
serde      = { version = "1.0", default-features = false, features = ["derive"] }
shlex      = "2.0.1"
thiserror  = "2.0.18"
toml       = { version = "0.8", default-features = false, features = ["parse"] }
which      = "8.0.4"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
